name: Teste if statement in workflow

on:
  push:
    branches:
      - main
    paths:
      - 'teste/**'
      - 'oi/**'

# teste https://github.com/Ofido/CodeWars/actions/runs/3615105962
# https://www.meziantou.net/executing-github-actions-jobs-or-steps-only-when-specific-files-change.htm
# https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow
# https://github.com/actions/runner/issues/2205

jobs:
  check-for-if-path:
    runs-on: ubuntu-latest
    outputs:
      teste_files_changed: ${{ steps.check_teste_files_changed.outputs.teste_files_changed }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - shell: pwsh
        id: check_teste_files_changed
        run: |
          $diff = git diff --name-only HEAD^ HEAD
          echo "diff"
          echo $diff
          $SourceDiff = $diff | Where-Object { $_ -match '^teste/' }
          echo "SourceDiff"
          echo $SourceDiff
          $HasDiff = $SourceDiff.Length -gt 0
          echo "HasDiff"
          echo $HasDiff
          echo "teste_files_changed=$HasDiff" >> $GITHUB_OUTPUT

  fake-build-teste-files:
    runs-on: ubuntu-latest
    needs: [check-for-if-path]
    # if https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution#example-only-run-job-for-specific-repository
    # if doc https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsif
    if: needs.check-for-if-path.outputs.teste_files_changed == 'True'
    steps:
      - run: |
          echo "Hi"


  this-will-run:
    runs-on: ubuntu-latest
    needs: [fake-build-teste-files]
    if: always() && needs.Skipped-Job.result != 'failure'
    steps:
      - run: |
          echo "Hi 2"