name: Teste if statement in workflow

on:
  push:
    branches:
      - main
    paths:
      - 'teste/**'
      - 'oi/**'

jobs:
  check-for-if-path:
    runs-on: ubuntu-latest
    outputs:
      teste_files_changed: ${{ steps.check_teste_files_changed.outputs.teste_files_changed }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - shell: pwsh
        id: check_teste_files_changed
        run: |
          $diff = git diff --name-only HEAD^ HEAD
          echo "diff"
          echo $diff
          $SourceDiff = $diff | Where-Object { $_ -match '^teste/' }
          echo "SourceDiff"
          echo $SourceDiff
          $HasDiff = $SourceDiff.Length -gt 0
          echo "HasDiff"
          echo $HasDiff
          echo "teste_files_changed=$HasDiff" >> $GITHUB_OUTPUT

  fake-build-teste-files:
    runs-on: ubuntu-latest
    needs: [check-for-if-path]
    if: needs.check-for-if-path.outputs.teste_files_changed == 'True'
    steps:
      - run: |
          echo "Hi"


  this-will-run:
    runs-on: ubuntu-latest
    needs: [fake-build-teste-files]
    steps:
      - run: |
          echo "Hi 2"