name: Teste if statement in workflow

on:
  push:
    branches:
      - main
    paths:
      - 'teste/**'

jobs:
  check-for-if-path:
    runs-on: ubuntu-latest
      outputs:
        teste_files_changed: ${{ steps.check_teste_files_changed.outputs.teste_files_changed }}
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 2

        - shell: pwsh
          id: check_teste_files_changed
          run: |
            $diff = git diff --name-only HEAD^ HEAD
            $SourceDiff = $diff | Where-Object { $_ -match '^teste/' }
            $HasDiff = $SourceDiff.Length -gt 0
            Write-Host "::set-output name=teste_files_changed::$HasDiff"

  fake-build-teste-files:
    runs-on: ubuntu-latest
    needs: [check-for-if-path]
    if: needs.check-for-if-path.outputs.teste_files_changed == 'True'
    steps:
      - uses: actions/checkout@v2
        run: |
          echo "Hi"


  this-will-run:
    runs-on: ubuntu-latest
    needs: [fake-build-teste-files]
    steps:
      - uses: actions/checkout@v2
        run: |
          echo "Hi"